# Colors... all the colors. 
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm*:RGB"
set -ag terminal-overrides ",alacritty:RGB"

# Status line color changes
set -g status-right "%d-%b-%y %H:%M"
set -g status-style fg="#5c6a72",bg="#fdf6e3"
set -g window-status-style fg="#5c6a72",bg="#fdf6e3"
setw -g window-status-current-style fg="#fdf6e3",bg="#3a94c5"

# Pane border and color settings
setw -g pane-border-style fg="#5c6a72",bg="#fdf6e3"
setw -g pane-active-border-style fg="#dfa000",bg="#fdf6e3"
