[colors.primary]
foreground = "0x93a1a1"
background = "0xfdf6e3"

[colors.cursor]
text = "0x2c323c"
cursor = "0x93a1a1"

[colors.selection]
foreground = "0x839496"
background = "0x93a1a1"

[colors.normal]
black = "0x2c323c"
white = "0x5c6370"
red = "0xdc322f"
green = "0x859900"
yellow = "0xb58900"
blue = "0x268bd2"
magenta = "0xd33682"
cyan = "0x2aa198"
