[colors.cursor]
cursor = "0x93a1a1"
text = "0x2c323c"

[colors.normal]
black = "0xfdf6e3"
base0 = "0x657b83"
base00 = "0x839496"
base01 = "0x93a1a1"
base02 = "0xeee8d5"
base03 = "0xfdf6e3"
base1 = "0x586e75"
base2 = "0x073642"
base3 = "0x002b36"
black = "0x2c323c"
blue = "0x268bd2"
cyan = "0x2aa198"
err_bg = "0xfdf6e3"
green = "0x859900"
magenta = "0xd33682"
orange = "0xcb4b16"
red = "0xdc322f"
violet = "0x6c71c4"
white = "0x5c6370"
yellow = "0xb58900"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[colors.selection]
background = "0x93a1a1"
foreground = "0x839496"
