name: Sync main to light 
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Sync main to light
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: light
          message: Merge  back into light mode
          github_token: ${{ github.token }}
